const Trip = require("../models/Trip");
const Expense = require("../models/Expense");
const Maintenance = require("../models/Maintenance");
const Vehicle = require("../models/Vehicle");

/**
 * Calculates the distance travelled for a single trip.
 * @param {string} tripId - MongoDB ObjectId of the trip.
 * @returns {Promise<number>} Distance in odometer units (endOdometer - startOdometer).
 */
const calculateDistanceForTrip = async (tripId) => {
    const trip = await Trip.findById(tripId);
    if (!trip) {
        throw new Error(`Trip not found: ${tripId}`);
    }
    if (trip.startOdometer === undefined || trip.startOdometer === null) {
        throw new Error(`Trip ${tripId} is missing startOdometer.`);
    }
    if (trip.endOdometer === undefined || trip.endOdometer === null) {
        throw new Error(`Trip ${tripId} is missing endOdometer. Trip may not be completed yet.`);
    }
    return trip.endOdometer - trip.startOdometer;
};

/**
 * Calculates fuel efficiency (km per unit fuel cost) for a vehicle.
 * Derives total distance from Completed trips and total fuel cost from Expense.fuelCost.
 * Note: Expense is linked via tripId, so we collect all completed trip IDs first.
 * Falls back to 0 if no fuel cost exists (divide-by-zero guard).
 * @param {string} vehicleId - MongoDB ObjectId of the vehicle.
 * @returns {Promise<number>} km per unit of fuel cost (distance / fuelCost).
 */
const calculateFuelEfficiency = async (vehicleId) => {
    const vehicle = await Vehicle.findById(vehicleId);
    if (!vehicle) {
        throw new Error(`Vehicle not found: ${vehicleId}`);
    }

    // Get all completed trips for this vehicle.
    const completedTrips = await Trip.find({
        vehicleId,
        status: "Completed",
        startOdometer: { $ne: null },
        endOdometer: { $ne: null },
    });

    const totalDistance = completedTrips.reduce(
        (sum, trip) => sum + (trip.endOdometer - trip.startOdometer),
        0
    );

    // Derive total fuel cost from Expense records linked to those trips.
    const tripIds = completedTrips.map((t) => t._id);
    const expenses = await Expense.find({ tripId: { $in: tripIds } });
    const totalFuelCost = expenses.reduce((sum, e) => sum + (e.fuelCost || 0), 0);

    // Divide-by-zero guard.
    if (totalFuelCost === 0) {
        return 0;
    }

    return totalDistance / totalFuelCost;
};

/**
 * Calculates the total operational cost for a vehicle.
 * Sums Maintenance.cost + Expense.fuelCost + Expense.maintenanceCost
 * for all records associated with the vehicle.
 * @param {string} vehicleId - MongoDB ObjectId of the vehicle.
 * @returns {Promise<number>} Total operational cost.
 */
const calculateTotalOperationalCost = async (vehicleId) => {
    const vehicle = await Vehicle.findById(vehicleId);
    if (!vehicle) {
        throw new Error(`Vehicle not found: ${vehicleId}`);
    }

    // Sum direct maintenance costs from Maintenance model.
    const maintenanceRecords = await Maintenance.find({ vehicleId });
    const maintenanceCost = maintenanceRecords.reduce(
        (sum, record) => sum + (record.cost || 0),
        0
    );

    // Sum fuel and maintenance costs from Expense records linked to this vehicle's trips.
    const vehicleTrips = await Trip.find({ vehicleId });
    const tripIds = vehicleTrips.map((t) => t._id);
    const expenses = await Expense.find({ tripId: { $in: tripIds } });

    const expenseFuelCost = expenses.reduce((sum, e) => sum + (e.fuelCost || 0), 0);
    const expenseMaintenanceCost = expenses.reduce(
        (sum, e) => sum + (e.maintenanceCost || 0),
        0
    );

    return maintenanceCost + expenseFuelCost + expenseMaintenanceCost;
};

/**
 * Calculates the Return on Investment (ROI) for a vehicle.
 * Formula: ROI = (revenue - totalOperationalCost) / acquisitionCost
 * @param {string} vehicleId       - MongoDB ObjectId of the vehicle.
 * @param {number} acquisitionCost - Original purchase/acquisition cost of the vehicle.
 * @param {number} revenue         - Total revenue generated by this vehicle.
 * @returns {Promise<number>} ROI as a decimal (e.g. 0.25 = 25% ROI).
 */
const calculateVehicleROI = async (vehicleId, acquisitionCost, revenue) => {
    if (!acquisitionCost || acquisitionCost <= 0) {
        throw new Error(
            `Invalid acquisitionCost: must be a positive number. Received: ${acquisitionCost}`
        );
    }

    const totalCost = await calculateTotalOperationalCost(vehicleId);
    const roi = (revenue - totalCost) / acquisitionCost;

    return roi;
};

module.exports = {
    calculateDistanceForTrip,
    calculateFuelEfficiency,
    calculateTotalOperationalCost,
    calculateVehicleROI,
};
